version: "3.8"

services:
  app:
    container_name: deploy-manager
    build: .
    ports:
      - "60534:3000" # Port exposé http://localhost:60534
    volumes:
      - ./src:/app
      - /app/node_modules       # Empêche conflit entre host et container
      - ./src/config/machines.json:/src/config/machines.json  # ← Lien vers fichier
    working_dir: /app
    command: sh -c "npm install && npm run start"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
